import type { Service } from "./types";

export const SEED_SERVICES: Service[] = [
  {
    slug: "market-insight",
    name: "AuraPredict Market Insight",
    description:
      "Paid oracle receipt & prediction-market insight API. Returns live market odds, evidence quality and a resolution-risk score, sourced from the AuraPredict indexer on Arc.",
    category: "market-insight",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "AuraPredict",
    price: "0.01",
    method: "GET",
    endpoint: "/api/premium/market-insight",
    docsUrl: "https://aurapredict.xyz",
    tags: ["prediction", "odds", "resolution-risk", "oracle"],
    verified: true,
    sampleResponse: {
      market: "Will ETH close above $4000 on 2026-07-01?",
      yesOdds: 0.62,
      noOdds: 0.38,
      evidenceQuality: "high",
      resolutionRisk: 0.12,
      source: "aurapredict-indexer",
    },
    active: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    slug: "oracle-check",
    name: "Crypto Price Oracle Check",
    description:
      "Objective oracle check for crypto spot prices with confidence score. Designed for agents resolving objective markets or triggering settlement.",
    category: "oracle",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "OracleWorks",
    price: "0.005",
    method: "GET",
    endpoint: "/api/premium/oracle-check",
    tags: ["price", "spot", "confidence", "settlement"],
    verified: true,
    sampleResponse: { symbol: "ETH", price: 3984.21, confidence: 0.98 },
    active: true,
    createdAt: "2026-06-03T00:00:00.000Z",
  },
  {
    slug: "summarize",
    name: "AI Document Summarizer",
    description:
      "Compresses long text into a structured summary with key points. Pay-per-call, no API key, no subscription.",
    category: "ai",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "BriefBot",
    price: "0.02",
    method: "POST",
    endpoint: "/api/premium/summarize",
    tags: ["llm", "summary", "nlp"],
    verified: true,
    sampleResponse: { summary: "3-bullet structured summary…", tokens: 512 },
    active: true,
    createdAt: "2026-06-05T00:00:00.000Z",
  },
  {
    slug: "dataset",
    name: "Crypto Fear & Greed Dataset",
    description:
      "7-day history of the Crypto Fear & Greed Index. Useful for agents timing entries, managing risk, or training sentiment models.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "ChainLabs",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/dataset",
    tags: ["analytics", "sentiment", "fear-greed", "history"],
    verified: true,
    sampleResponse: { day: "2026-06-18", fearGreedValue: 62, label: "Greed" },
    active: true,
    createdAt: "2026-06-08T00:00:00.000Z",
  },
  {
    slug: "sentiment",
    name: "Crypto Market Sentiment",
    description:
      "Real-time Crypto Fear & Greed Index with signal interpretation. One call returns current score, label, and actionable signal for AI agents.",
    category: "ai",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "SentimentAI",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/sentiment",
    tags: ["sentiment", "fear-greed", "signal", "market"],
    verified: true,
    sampleResponse: { sentiment: "Greed", score: 67, signal: "greed" },
    active: true,
    createdAt: "2026-06-10T00:00:00.000Z",
  },
  {
    slug: "trending",
    name: "Trending Coins Right Now",
    description:
      "Top 5 trending coins on CoinGecko in the last 24h — name, symbol, market cap rank and 24h price change. Perfect for agents scanning momentum.",
    category: "market-insight",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "TrendBot",
    price: "0.003",
    method: "GET",
    endpoint: "/api/premium/trending",
    tags: ["trending", "coins", "momentum", "coingecko"],
    verified: false,
    sampleResponse: { coins: [{ rank: 1, name: "Bitcoin", symbol: "BTC" }] },
    active: true,
    createdAt: "2026-06-12T00:00:00.000Z",
  },
  {
    slug: "weather",
    name: "Global Weather Now",
    description:
      "Live temperature, humidity and wind for major cities. Add ?city=tokyo (hanoi, singapore, tokyo, london, newyork). Great for agents that act on local conditions.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "WeatherWorks",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/weather",
    tags: ["weather", "temperature", "cities", "realtime"],
    verified: true,
    sampleResponse: { city: "Hanoi", temperatureC: 31, humidityPct: 70, windSpeedKmh: 8 },
    active: true,
    createdAt: "2026-06-14T00:00:00.000Z",
  },
  {
    slug: "fx-rates",
    name: "USD Foreign Exchange Rates",
    description:
      "Latest USD exchange rates (EUR, GBP, JPY, VND, SGD, CNY) sourced from European Central Bank data. For agents pricing cross-border or multi-currency flows.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "FXFeed",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/fx-rates",
    tags: ["forex", "currency", "usd", "rates"],
    verified: true,
    sampleResponse: { base: "USD", rates: { EUR: 0.92, VND: 25400, JPY: 157 } },
    active: true,
    createdAt: "2026-06-16T00:00:00.000Z",
  },
  {
    slug: "ip-info",
    name: "IP Geolocation Lookup",
    description:
      "Resolve any IP address to country, city, ISP, and coordinates. Add ?ip=8.8.8.8 to look up a specific IP, or omit to auto-detect the caller's location.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "GeoNet",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/ip-info",
    tags: ["geolocation", "ip", "country", "isp"],
    verified: true,
    sampleResponse: { ip: "8.8.8.8", country: "United States", city: "Mountain View", isp: "Google LLC" },
    active: true,
    createdAt: "2026-06-17T00:00:00.000Z",
  },
  {
    slug: "holidays",
    name: "Public Holidays by Country",
    description:
      "Public holidays for any country this year. Add ?country=VN (ISO 2-letter code). Supports US, VN, GB, JP, DE, FR, SG, AU and 100+ more. Useful for scheduling agents.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "CalendarAPI",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/holidays",
    tags: ["calendar", "holidays", "country", "schedule"],
    verified: true,
    sampleResponse: { country: "VN", year: 2026, holidays: [{ date: "2026-01-01", name: "New Year's Day" }] },
    active: true,
    createdAt: "2026-06-17T06:00:00.000Z",
  },
  {
    slug: "country-info",
    name: "Country Facts & Stats",
    description:
      "Population, capital, region, languages, currencies and area for any country. Add ?country=Vietnam. Perfect for agents doing geo-targeted research or localisation.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "GeoNet",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/country-info",
    tags: ["country", "population", "geography", "stats"],
    verified: true,
    sampleResponse: { name: "Vietnam", capital: "Hanoi", population: 97338579, region: "Asia" },
    active: true,
    createdAt: "2026-06-17T12:00:00.000Z",
  },
  {
    slug: "mempool",
    name: "Bitcoin Mempool & Fee Tracker",
    description:
      "Live Bitcoin network fee rates (sat/vB) for fastest, half-hour, 1-hour, and economy confirmation. Includes current block height. Essential for agents quoting or sending BTC.",
    category: "oracle",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "MempoolWatch",
    price: "0.003",
    method: "GET",
    endpoint: "/api/premium/mempool",
    tags: ["bitcoin", "fees", "mempool", "btc"],
    verified: true,
    sampleResponse: { fees: { fastestSat: 22, economySat: 4 }, blockHeight: 900123 },
    active: true,
    createdAt: "2026-06-17T18:00:00.000Z",
  },
  {
    slug: "joke",
    name: "Random Dev Joke",
    description:
      "A safe, randomly-picked programming or tech joke. Great for adding personality to agent responses — and the cheapest way to test the x402 payment flow at $0.001 per call.",
    category: "ai",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "JokeBot",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/joke",
    tags: ["fun", "joke", "programming", "demo"],
    verified: false,
    sampleResponse: { category: "Programming", joke: "Why do programmers prefer dark mode? Because light attracts bugs." },
    active: true,
    createdAt: "2026-06-18T00:00:00.000Z",
  },
];
