import type { Service } from "./types";

export const SEED_SERVICES: Service[] = [
  {
    slug: "market-insight",
    name: "AuraPredict Market Insight",
    description:
      "Paid oracle receipt & prediction-market insight API. Returns live market odds, evidence quality and a resolution-risk score, sourced from the AuraPredict indexer on Arc.",
    category: "market-insight",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "AuraPredict",
    price: "0.01",
    method: "GET",
    endpoint: "/api/premium/market-insight",
    docsUrl: "https://aurapredict.xyz",
    tags: ["prediction", "odds", "resolution-risk", "oracle"],
    verified: true,
    sampleResponse: {
      market: "Will ETH close above $4000 on 2026-07-01?",
      yesOdds: 0.62,
      noOdds: 0.38,
      evidenceQuality: "high",
      resolutionRisk: 0.12,
      source: "aurapredict-indexer",
    },
    active: true,
    createdAt: "2026-06-01T00:00:00.000Z",
  },
  {
    slug: "oracle-check",
    name: "Crypto Price Oracle Check",
    description:
      "Objective oracle check for crypto spot prices with confidence score. Designed for agents resolving objective markets or triggering settlement.",
    category: "oracle",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "OracleWorks",
    price: "0.005",
    method: "GET",
    endpoint: "/api/premium/oracle-check",
    tags: ["price", "spot", "confidence", "settlement"],
    verified: true,
    sampleResponse: { symbol: "ETH", price: 3984.21, confidence: 0.98 },
    active: true,
    createdAt: "2026-06-03T00:00:00.000Z",
  },
  {
    slug: "summarize",
    name: "AI Document Summarizer",
    description:
      "Compresses long text into a structured summary with key points. Pay-per-call, no API key, no subscription.",
    category: "ai",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "BriefBot",
    price: "0.02",
    method: "POST",
    endpoint: "/api/premium/summarize",
    tags: ["llm", "summary", "nlp"],
    verified: true,
    sampleResponse: { summary: "3-bullet structured summary…", tokens: 512 },
    active: true,
    createdAt: "2026-06-05T00:00:00.000Z",
  },
  {
    slug: "dataset",
    name: "Crypto Fear & Greed Dataset",
    description:
      "7-day history of the Crypto Fear & Greed Index. Useful for agents timing entries, managing risk, or training sentiment models.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "ChainLabs",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/dataset",
    tags: ["analytics", "sentiment", "fear-greed", "history"],
    verified: true,
    sampleResponse: { day: "2026-06-18", fearGreedValue: 62, label: "Greed" },
    active: true,
    createdAt: "2026-06-08T00:00:00.000Z",
  },
  {
    slug: "sentiment",
    name: "Crypto Market Sentiment",
    description:
      "Real-time Crypto Fear & Greed Index with signal interpretation. One call returns current score, label, and actionable signal for AI agents.",
    category: "ai",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "SentimentAI",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/sentiment",
    tags: ["sentiment", "fear-greed", "signal", "market"],
    verified: true,
    sampleResponse: { sentiment: "Greed", score: 67, signal: "greed" },
    active: true,
    createdAt: "2026-06-10T00:00:00.000Z",
  },
  {
    slug: "trending",
    name: "Trending Coins Right Now",
    description:
      "Top 5 trending coins on CoinGecko in the last 24h — name, symbol, market cap rank and 24h price change. Perfect for agents scanning momentum.",
    category: "market-insight",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "TrendBot",
    price: "0.003",
    method: "GET",
    endpoint: "/api/premium/trending",
    tags: ["trending", "coins", "momentum", "coingecko"],
    verified: false,
    sampleResponse: { coins: [{ rank: 1, name: "Bitcoin", symbol: "BTC" }] },
    active: true,
    createdAt: "2026-06-12T00:00:00.000Z",
  },
  {
    slug: "weather",
    name: "Global Weather Now",
    description:
      "Live temperature, humidity and wind for major cities. Add ?city=tokyo (hanoi, singapore, tokyo, london, newyork). Great for agents that act on local conditions.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "WeatherWorks",
    price: "0.001",
    method: "GET",
    endpoint: "/api/premium/weather",
    tags: ["weather", "temperature", "cities", "realtime"],
    verified: true,
    sampleResponse: { city: "Hanoi", temperatureC: 31, humidityPct: 70, windSpeedKmh: 8 },
    active: true,
    createdAt: "2026-06-14T00:00:00.000Z",
  },
  {
    slug: "fx-rates",
    name: "USD Foreign Exchange Rates",
    description:
      "Latest USD exchange rates (EUR, GBP, JPY, VND, SGD, CNY) sourced from European Central Bank data. For agents pricing cross-border or multi-currency flows.",
    category: "data",
    sellerAddress: "0x89100844705F50e9566386B908059B27041804D0",
    sellerName: "FXFeed",
    price: "0.002",
    method: "GET",
    endpoint: "/api/premium/fx-rates",
    tags: ["forex", "currency", "usd", "rates"],
    verified: true,
    sampleResponse: { base: "USD", rates: { EUR: 0.92, VND: 25400, JPY: 157 } },
    active: true,
    createdAt: "2026-06-16T00:00:00.000Z",
  },
];
